# Generated by Django 2.0.4 on 2018-04-13 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_product_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Store',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_name',
            new_name='name',
        ),
    ]
