# Generated by Django 2.0.4 on 2018-04-13 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20180412_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='pname',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='name',
            new_name='sname',
        ),
    ]
